language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install numpy
  - pip install -r requirements.txt
  - python manage.py init
script:
  - nosetests
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#lqdn-memopol"